# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19lTJHcNTtAQsKHngl_Yajm7jStFdNbtO

###Função Afim
"""

import matplotlib.pyplot as plt
import numpy as np
import math

X = np.asarray([-5,-4,-3,-2,-1,0,1,2,3,4,5])
afim = 2*X
plt.plot(X, afim)

"""### Função Quadratica"""

X = np.asarray([-5,-4,-3,-2,-1,0,1,2,3,4,5])
quadratica = 5*X**2 + 3
plt.plot(X, quadratica)

"""### Função Polinomial"""

X = np.asarray([-5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5])
polinomial = X**7 - 3
plt.plot(X, polinomial)

"""### Função Modular"""

X = np.asarray([-5,-4,-3,-2,-1,0,1,2,3,4,5])
modular = abs(X)**2 - 4*abs(X) + 6
plt.plot(X, modular)

"""### Função exponencial"""

X = np.asarray([1,2,3,4,5,6,7,8,9,10])
exponencial = 5**X
plt.plot(X, exponencial)

"""### Função Logaritmica"""

X = np.asarray([1,2,3,4,5,6,7,8,9,10])
base = 4
logaritmica = np.log(X) / np.log(base)
plt.plot(logaritmica)

"""### Função Trigonometrica"""

from sympy import *
from sympy.plotting import *
x = Symbol('x')

seno = sin(x)
coseno = cos(x)
tangente = tan(x)


plot(seno,coseno,tangente)

"""### Transformada na função Polinomial"""

X = np.asarray([-5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5])
Transformadapolinomial = X**7 - 3 + 
plt.plot(X, Transformadapolinomial)

"""### Transformada na função Afim"""

X = np.asarray([-5,-4,-3,-2,-1,0,1,2,3,4,5])
tranformadaAfim = 2*X + 4*X
plt.plot(X, tranformadaAfim)